import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "../components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Skill Bridge",
  description: "Generated by Skill Bridge",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#0a0a14] text-white antialiased`}
      >
        <time dateTime="2016-10-25"/>        
        
        {/* Global Background Glow */}
        <div className="fixed inset-0 -z-10">
          <div className="absolute top-[-200px] right-[-200px] h-[500px] w-[500px] rounded-full bg-orange-500/20 blur-[120px]" />
          <div className="absolute bottom-[-200px] left-[-200px] h-[500px] w-[500px] rounded-full bg-purple-500/20 blur-[120px]" />
        </div>

        {/* Page Content */}
        <div className="container mx-auto px-4">
          {children}
        </div>
        <Toaster></Toaster>
      </body>
    </html>
  );
}
